#ifndef GUARD_CONSTANTS_BEST_OF_THREE_H
#define GUARD_CONSTANTS_BEST_OF_THREE_H

#define BO3_ROUND_ABORTED 0
#define BO3_ROUND_CONTINUE 1
#define BO3_SERIES_WON 2
#define BO3_SERIES_LOST 3

#define BO3_CANCEL_ABORT 0
#define BO3_CANCEL_WHITEOUT 1

#endif // GUARD_CONSTANTS_BEST_OF_THREE_H
