#ifndef GUARD_CONSTANTS_GAME_CORNER_GACHA_H
#define GUARD_CONSTANTS_GAME_CORNER_GACHA_H

enum {
    GACHA_BASIC = 1,
    GACHA_GREAT,
    GACHA_ULTRA,
    GACHA_MASTER,
    GACHA_COUNT,
};

enum {
    RARITY_COMMON,
    RARITY_UNCOMMON,
    RARITY_RARE,
    RARITY_ULTRA_RARE,
    RARITY_COUNT,
};

#endif // GUARD_CONSTANTS_GAME_CORNER_GACHA_H
