#ifndef GUARD_CONSTANTS_INTERNET_OPTIONS_H
#define GUARD_CONSTANTS_INTERNET_OPTIONS_H

enum {
    INTERNET_OPTIONS_NONE,
    INTERNET_TEST_CONNECTION,
    INTERNET_GET_GIFT_MON,
    INTERNET_OPTIONS_END,
};

enum {
    INTERNET_STATE_NONE,
    INTERNET_STATE_IDLE,
    INTERNET_STATE_MA_ERR,
    INTERNET_STATE_INPUT_ERR,
    INTERNET_STATE_SUCCESS,
    INTERNET_STATE_SENT_TO_PARTY,
    INTERNET_STATE_SENT_TO_PC,
    INTERNET_STATE_PC_FULL,
    INTERNET_STATE_END,
};

#endif //GUARD_CONSTANTS_INTERNET_OPTIONS_H