MemoryGirl_Text_ICanReadMonMemory::
	.string "Hi, hi! I'm the Memory Girl!\n"
	.string "I can read Pokémon memories.\p"
	.string "Do you want to know the\n"
	.string "memory of your Pokémon?$"

MemoryGirl_Text_ReadWhichMonMemory::
	.string "OK! Which Pokémon's memory\n"
	.string "do you want to know?$"

MemoryGirl_Text_ComeBackAnytime::
	.string "Come back anytime!$"

MemoryGirl_Text_ThatIsJustAnEgg::
	.string "I can't read that.\n"
	.string "It's just an EGG!$"

MemoryGirl_Text_LetsSeeWhatElse::
	.string "In it's memory I see…$"

MemoryGirl_Text_AndAlso::
	.string "I also see…$"

MemoryGirl_Text_NoMemoriesToRead::
	.string "That's all…\p"
	.string "It looks like {STR_VAR_1}\n"
	.string "hasn't done much.$"

MemoryGirl_Text_YouveHadGreatTimes::
	.string "{STR_VAR_1} has shared some great\n"
	.string "memories with you!$"

MemoryGirl_Text_WellTravelledMon::
	.string "{STR_VAR_1} has shared some great\n"
	.string "memories with plenty of trainers!$"

MemoryGirl_Text_PleaseGiveItThisHistoricRibbon::
	.string "As its reward, please give it this\n"
	.string "HISTORIC RIBBON.$"

MemoryGirl_Text_PleaseGiveItThisTravellerRibbon::
	.string "As its reward, please give it this\n"
	.string "TRAVELLER RIBBON.$"

MemoryGirl_Text_ReceivedHistoricRibbon::
	.string "{PLAYER} received the HISTORIC RIBBON.$"

MemoryGirl_Text_ReceivedTravellerRibbon::
	.string "{PLAYER} received the TRAVELLER RIBBON.$"

MemoryGirl_Text_PutHistoricRibbonOnMon::
	.string "{PLAYER} put the HISTORIC RIBBON\n"
	.string "on {STR_VAR_1}.$"

MemoryGirl_Text_PutTravellerRibbonOnMon::
	.string "{PLAYER} put the TRAVELLER RIBBON\n"
	.string "on {STR_VAR_1}.$"

MemoryStrings_NoMemory::
	.string ".$"

MemoryStrings_TransferedOverWonderTrade::
	.string "{STR_VAR_1} was transfered over\n"
	.string "wonder trade.$"

MemoryStrings_TransferedOverLinkTrade::
	.string "{STR_VAR_1} was transfered over\n"
	.string "link trade.$"

MemoryStrings_WonACoolContest::
	.string "{STR_VAR_1} showed an incredible display\n"
	.string "of coolness in a contest{STR_VAR_3}$"

MemoryStrings_WonABeautyContest::
 	.string "{STR_VAR_1} showed an incredible display\n"
	.string "of beauty in a contest{STR_VAR_3}$"

MemoryStrings_WonACuteContest::
	.string "{STR_VAR_1} showed an incredible display\n"
	.string "of cuteness in a contest{STR_VAR_3}$"

MemoryStrings_WonACleverContest::
	.string "{STR_VAR_1} showed an incredible display\n"
	.string "of smarts in a contest{STR_VAR_3}$"

MemoryStrings_WonAToughContest::
	.string "{STR_VAR_1} showed an incredible display\n"
	.string "of strength in a contest{STR_VAR_3}$"

MemoryStrings_AteACoolPokeblock::
	.string "{STR_VAR_1} felt cool after eating\n"
	.string "a Pokéblock{STR_VAR_3}$"

MemoryStrings_AteABeautyPokeblock::
	.string "{STR_VAR_1} felt beautiful after eating\n"
	.string "a Pokéblock{STR_VAR_3}$"

MemoryStrings_AteACutePokeblock::
	.string "{STR_VAR_1} felt cute after eating\n"
	.string "a Pokéblock{STR_VAR_3}$"

MemoryStrings_AteACleverPokeblock::
	.string "{STR_VAR_1} felt clever after eating\n"
	.string "a Pokéblock{STR_VAR_3}$"

MemoryStrings_AteAToughPokeblock::
	.string "{STR_VAR_1} felt tough after eating\n"
	.string "a Pokéblock{STR_VAR_3}$"

MemoryStrings_AteADislikedPokeblock::
	.string "{STR_VAR_1} felt disgusted after eating\n"
	.string "a Pokéblock{STR_VAR_3}$"

MemoryStrings_AteALovedPokeblock::
	.string "{STR_VAR_1} felt incredible after eating\n"
	.string "a Pokéblock{STR_VAR_3}$"

MemoryStrings_MaxedOutSheen::
	.string "{STR_VAR_1} reached peak form after\n"
	.string "eating a Pokéblock{STR_VAR_3}$"

MemoryStrings_FoughtRoxanneGym::
	.string "{STR_VAR_1} fought and defeated Gym\n"
	.string "Leader Roxanne{STR_VAR_3}$"

MemoryStrings_FoughtBrawlyGym::
	.string "{STR_VAR_1} fought and defeated Gym\n"
	.string "Leader Brawly{STR_VAR_3}$"

MemoryStrings_FoughtWattsonGym::
	.string "{STR_VAR_1} fought and defeated Gym\n"
	.string "Leader Wattson{STR_VAR_3}$"

MemoryStrings_FoughtFlanneryGym::
	.string "{STR_VAR_1} fought and defeated Gym\n"
	.string "Leader Flannery{STR_VAR_3}$"

MemoryStrings_FoughtNormanGym::
	.string "{STR_VAR_1} fought and defeated Gym\n"
	.string "Leader Norman{STR_VAR_3}$"

MemoryStrings_FoughtWinonaGym::
	.string "{STR_VAR_1} fought and defeated Gym\n"
	.string "Leader Winona{STR_VAR_3}$"

MemoryStrings_FoughtTateAndLizaGym::
	.string "{STR_VAR_1} fought and defeated Gym\n"
	.string "Leader Tate and Liza{STR_VAR_3}$"

MemoryStrings_FoughtWallaceGym::
	.string "{STR_VAR_1} fought and defeated Gym\n"
	.string "Leader Wallace{STR_VAR_3}$"

MemoryStrings_FoughtTheEliteFour::
	.string "{STR_VAR_1} fought and defeated The\n"
	.string "Elite Four{STR_VAR_3}$"

MemoryStrings_FoughtASignificant::
	.string "{STR_VAR_1} fought and defeated a\n"
	.string "mysterious trainer{STR_VAR_3}$"

MemoryStrings_EarnedSilverFrontier::
	.string "{STR_VAR_1} battled and earned a\n"
	.string "Silver Frontier medal{STR_VAR_3}$"

MemoryStrings_CaughtALegendary::
	.string "{STR_VAR_1} helped to capture a\n"
	.string "Legendary Pokémon{STR_VAR_3}$"

MemoryStrings_DefendedChampionTitle::
	.string "{STR_VAR_1} defended the Championship\n"
	.string "Title{STR_VAR_3}$"

MemoryStrings_WonAMasterContest::
	.string "{STR_VAR_1} put on a masterful contest\n"
	.string "performance{STR_VAR_3}$"

MemoryStrings_SavedTheWorld::
	.string "{STR_VAR_1} awoke a legendary Pokémon\n"
	.string "and saved the world{STR_VAR_3}$"

MemoryStrings_EarnedGoldFrontier::
	.string "{STR_VAR_1} battled and earned a\n"
	.string "Gold Frontier medal{STR_VAR_3}$"
