MemoryGirl_Text_ICanReadMonMemory::
	.string "Hi, hi! I'm the Memory Girl!\n"
	.string "I can read Pokémon memories.\p"
	.string "Do you want to know the\n"
	.string "memory of your Pokémon?$"

MemoryGirl_Text_ReadWhichMonMemory::
	.string "OK! Which Pokémon's memory\n"
	.string "do you want to know?$"

MemoryGirl_Text_ComeBackAnytime::
	.string "Come back anytime!$"

MemoryGirl_Text_ThatIsJustAnEgg::
	.string "I can't read that.\n"
	.string "It's just an EGG!$"

MemoryGirl_Text_LetsSeeWhatElse::
  .string "Let's see what else…$"

MemoryGirl_Text_NoMemoriesToRead::
  .string "Hmmm… it looks like {STR_VAR_1}\n"
  .string "hasn't done much.\p"
	.string "How sad!$"

MemoryStrings_NoMemory::
  .string ".$"

MemoryStrings_TransferedOverWonderTrade::
	.string "{STR_VAR_1} was transfered over\n"
	.string "wonder trade.$"

MemoryStrings_TransferedOverLinkTrade::
	.string "{STR_VAR_1} was transfered over\n"
	.string "link trade.$"

MemoryStrings_WonACoolContest::
  .string "{STR_VAR_1} showed an incredible\n"
	.string "display of coolness{STR_VAR_3}$"

MemoryStrings_WonABeautyContest::
  .string "{STR_VAR_1} showed an incredible\n"
	.string "display of beauty{STR_VAR_3}$"

MemoryStrings_WonACuteContest::
  .string "{STR_VAR_1} showed an incredible\n"
	.string "display of cuteness{STR_VAR_3}$"

MemoryStrings_WonACleverContest::
  .string "{STR_VAR_1} showed an incredible\n"
	.string "display of cleverness{STR_VAR_3}$"

MemoryStrings_WonAToughContest::
  .string "{STR_VAR_1} showed an incredible\n"
	.string "display of toughness{STR_VAR_3}$"

MemoryStrings_AteACoolPokeblock::
  .string "{STR_VAR_1} felt cool after\n"
	.string "eating a berry{STR_VAR_3}$"

MemoryStrings_AteABeautyPokeblock::
  .string "{STR_VAR_1} felt beautiful after\n"
	.string "eating a berry{STR_VAR_3}$"

MemoryStrings_AteACutePokeblock::
  .string "{STR_VAR_1} felt cute after\n"
	.string "eating a berry{STR_VAR_3}$"

MemoryStrings_AteACleverPokeblock::
  .string "{STR_VAR_1} felt clever after\n"
	.string "eating a berry{STR_VAR_3}$"

MemoryStrings_AteAToughPokeblock::
  .string "{STR_VAR_1} felt tough after\n"
	.string "eating a berry{STR_VAR_3}$"

MemoryStrings_AteADislikedPokeblock::
  .string "{STR_VAR_1} felt disgusted after\n"
	.string "eating a berry{STR_VAR_3}$"

MemoryStrings_AteALovedPokeblock::
  .string "{STR_VAR_1} felt incredible after\n"
	.string "eating a berry{STR_VAR_3}$"

MemoryStrings_MaxedOutSheen::
  .string "{STR_VAR_1} reached peak physical form\n"
	.string "eating a berry{STR_VAR_3}$"

MemoryStrings_FoughtRoxanneGym::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "Gym Leader Roxanne{STR_VAR_3}$"

MemoryStrings_FoughtBrawlyGym::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "Gym Leader Brawly{STR_VAR_3}$"

MemoryStrings_FoughtWattsonGym::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "Gym Leader Wattson{STR_VAR_3}$"

MemoryStrings_FoughtFlanneryGym::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "Gym Leader Flannery{STR_VAR_3}$"

MemoryStrings_FoughtNormanGym::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "Gym Leader Norman{STR_VAR_3}$"

MemoryStrings_FoughtWinonaGym::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "Gym Leader Winona{STR_VAR_3}$"

MemoryStrings_FoughtTateAndLizaGym::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "Gym Leader Tate and Liza{STR_VAR_3}$"

MemoryStrings_FoughtWallaceGym::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "Gym Leader Wallace{STR_VAR_3}$"

MemoryStrings_FoughtTheEliteFour::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "The Elite Four{STR_VAR_3}$"

MemoryStrings_FoughtASignificant::
  .string "{STR_VAR_1} fought and defeated\n"
	.string "a mysterious trainer{STR_VAR_3}$"

MemoryStrings_EarnedSilverFrontier::
  .string "{STR_VAR_1} battled and earned\n"
	.string "a Silver Frontier medal{STR_VAR_3}$"

MemoryStrings_CaughtALegendary::
  .string "{STR_VAR_1} helped to capture\n"
	.string "a Legendary Pokémon{STR_VAR_3}$"

MemoryStrings_DefendedChampionTitle::
  .string "{STR_VAR_1} defended the\n"
	.string "championship title{STR_VAR_3}$"

MemoryStrings_WonAMasterContest::
  .string "{STR_VAR_1} put on a perfect\n"
	.string "contest performance{STR_VAR_3}$"

MemoryStrings_SavedTheWorld::
  .string "{STR_VAR_1} awoke a legendary\n"
	.string "Pokémon and saved the world{STR_VAR_3}$"

MemoryStrings_EarnedGoldFrontier::
  .string "{STR_VAR_1} battled and earned\n"
	.string "a Gold Frontier medal{STR_VAR_3}$"

MemoryStrings_ByX::
	.string "by {STR_VAR_2}."

MemoryStrings_WithX::
  .string "\lalongside {STR_VAR_2}."

MemoryStrings_GivenByX::
  .string "\lgiven by {STR_VAR_2}."
