gText_ImTheBattleMaster::
    .string "Greetings…\p"
    .string "I am the Battle Master.$"

gText_NoEffectiveCap::
    .string "There is no limit on your\n"
    .string "experience gains currently.$"

gText_EffectiveCap::
    .string "Your experience has a level cap\n"
    .string "up to “{STR_VAR_2}” currently.$"

gText_TurnLevelCapsOn::
    .string "Would you like me to add a\n"
    .string "level cap?$"

gText_TurnLevelCapsOff::
    .string "Would you like me to remove\n"
    .string "this level cap?$"

gText_OkItIsOn::
    .string "Ok…\p"
    .string "I have added the cap.$"

gText_OkItIsOff::
    .string "Ok…\p"
    .string "I have removed the cap.$"

gText_YouHaveOvercomeAllChallenges::
    .string "Seems you have overcome your\n"
    .string "Inexperience.\p"
    .string "I have nothing left to do\n"
    .string "for you.$"

gText_MoreChallengesAwait::
    .string "…More challenges and more\n"
    .string "rewards await you at the\p"
    .string "Battle Frontier.$"

gText_BattleMasterIntroduction::
    .string "…hm?\p"
    .string "I've never seen you before.\n"
    .string "and I always remember a face.$"

gText_BattleMasterGiveExpShare::
    .string "Please…\n"
    .string "Take this.$"

gText_BattleMasterPostExpShare::
    .string "This item will assist you\n"
    .string "in your travels.\p"
    .string "Even when you cannot\n"
    .string "reach me.\p"
    .string "Now…\n"
    .string "Back to business…$"

