Text_TestAPIWantToConnect::
    .string "Would you like to connect to the\n"
    .string "internet for a test?$"

Text_TestAPIConnecting::
	.string "CONNECTING…\n"
	.string "Don't turn off the power.$"

Text_TestAPIFailure::
    .string "ERROR!\n"
    .string "Failed without error code.$"

Text_TestAPIMaFailure::
    .string "ERROR!\n"
    .string "Failed with error from MA.$"

Text_TestAPIInputFailure::
    .string "ERROR!\n"
    .string "Failed with input error.$"

Text_TestAPISuccess::
    .string "SUCCESS!\n"
    .string "API Call passed.$"
