type MapLocation = [string, string]; // [mapId, mapName]

export const mapLocations: MapLocation[] = [
    ["MAP_ROUTE101", "Route 101"],
    ["MAP_ROUTE102", "Route 102"],
    ["MAP_ROUTE103", "Route 103"],
    ["MAP_ROUTE104", "Route 104"],
    ["MAP_ROUTE105", "Route 105"],
    ["MAP_ROUTE106", "Route 106"],
    ["MAP_ROUTE107", "Route 107"],
    ["MAP_ROUTE108", "Route 108"],
    ["MAP_ROUTE109", "Route 109"],
    ["MAP_ROUTE110", "Route 110"],
    ["MAP_ROUTE111", "Route 111"],
    ["MAP_ROUTE112", "Route 112"],
    ["MAP_ROUTE113", "Route 113"],
    ["MAP_ROUTE114", "Route 114"],
    ["MAP_ROUTE115", "Route 115"],
    ["MAP_ROUTE116", "Route 116"],
    ["MAP_ROUTE117", "Route 117"],
    ["MAP_ROUTE118", "Route 118"],
    ["MAP_ROUTE119", "Route 119"],
    ["MAP_ROUTE120", "Route 120"],
    ["MAP_ROUTE121", "Route 121"],
    ["MAP_ROUTE122", "Route 122"],
    ["MAP_ROUTE123", "Route 123"],
    ["MAP_ROUTE124", "Route 124"],
    ["MAP_ROUTE125", "Route 125"],
    ["MAP_ROUTE126", "Route 126"],
    ["MAP_ROUTE127", "Route 127"],
    ["MAP_ROUTE128", "Route 128"],
    ["MAP_ROUTE129", "Route 129"],
    ["MAP_ROUTE130", "Route 130"],
    ["MAP_ROUTE131", "Route 131"],
    ["MAP_ROUTE132", "Route 132"],
    ["MAP_ROUTE133", "Route 133"],
    ["MAP_ROUTE134", "Route 134"],
    ["MAP_PETALBURG_WOODS", "Petalburg Woods"],
    ["MAP_RUSTURF_TUNNEL", "Rusturf Tunnel"],
    ["MAP_GRANITE_CAVE_1F", "Granite Cave 1F"],
    ["MAP_GRANITE_CAVE_B1F", "Granite Cave B1F"],
    ["MAP_GRANITE_CAVE_B2F", "Granite Cave B2F"],
    ["MAP_GRANITE_CAVE_STEVENS_ROOM", "Granite Cave Stevens Room"],
    ["MAP_ABANDONED_SHIP_ROOMS_B1F", "Abandoned Ship Rooms B1F"],
    ["MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS", "Abandoned Ship Hidden Floor Corridors"],
    ["MAP_NEW_MAUVILLE_INSIDE", "New Mauville Inside"],
    ["MAP_NEW_MAUVILLE_ENTRANCE", "New Mauville Entrance"],
    ["MAP_MT_PYRE_2F", "Mt Pyre 2F"],
    ["MAP_MT_PYRE_4F", "Mt Pyre 4F"],
    ["MAP_MT_PYRE_5F", "Mt Pyre 5F"],
    ["MAP_MT_PYRE_EXTERIOR", "Mt Pyre Exterior"],
    ["MAP_MT_PYRE_SUMMIT", "Mt Pyre Summit"],
    ["MAP_SEAFLOOR_CAVERN_ROOM1", "Seafloor Cavern Room1"],
    ["MAP_SEAFLOOR_CAVERN_ROOM2", "Seafloor Cavern Room2"],
    ["MAP_SEAFLOOR_CAVERN_ROOM6", "Seafloor Cavern Room6"],
    ["MAP_SEAFLOOR_CAVERN_ROOM7", "Seafloor Cavern Room7"],
    ["MAP_SEAFLOOR_CAVERN_ROOM8", "Seafloor Cavern Room8"],
    ["MAP_VICTORY_ROAD_1F", "Victory Road 1F"],
    ["MAP_VICTORY_ROAD_B1F", "Victory Road B1F"],
    ["MAP_VICTORY_ROAD_B2F", "Victory Road B2F"],
    ["MAP_METEOR_FALLS_1F_1R", "Meteor Falls 1F 1R"],
    ["MAP_METEOR_FALLS_1F_2R", "Meteor Falls 1F 2R"],
    ["MAP_METEOR_FALLS_B1F_1R", "Meteor Falls B1F 1R"],
    ["MAP_METEOR_FALLS_B1F_2R", "Meteor Falls B1F 2R"],
    ["MAP_SAFARI_ZONE_SOUTH", "Safari Zone South"],
    ["MAP_SAFARI_ZONE_NORTH", "Safari Zone North"],
    ["MAP_SAFARI_ZONE_SOUTHWEST", "Safari Zone Southwest"],
    ["MAP_SAFARI_ZONE_SOUTHEAST", "Safari Zone Southeast"],
    ["MAP_MAGMA_HIDEOUT_1F", "Magma Hideout 1F"],
    ["MAP_MAGMA_HIDEOUT_3F_1R", "Magma Hideout 3F 1R"],
    ["MAP_MAGMA_HIDEOUT_3F_2R", "Magma Hideout 3F 2R"],
    ["MAP_MAGMA_HIDEOUT_3F_3R", "Magma Hideout 3F 3R"],
    ["MAP_MIRAGE_TOWER_1F", "Mirage Tower 1F"],
    ["MAP_MIRAGE_TOWER_2F", "Mirage Tower 2F"],
    ["MAP_MIRAGE_TOWER_3F", "Mirage Tower 3F"],
    ["MAP_MIRAGE_TOWER_4F", "Mirage Tower 4F"],
    ["MAP_DESERT_RUINS", "Desert Ruins"],
    ["MAP_ALTERING_CAVE", "Altering Cave"],
    ["MAP_DESERT_UNDERPASS", "Desert Underpass"],
    ["MAP_UNDERWATER_ROUTE126", "Underwater Route126"],
    ["MAP_CAVE_OF_ORIGIN_ENTRANCE", "Cave Of Origin Entrance"],
    ["MAP_CAVE_OF_ORIGIN_1F", "Cave Of Origin 1F"],
    ["MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1", "Cave Of Origin Unused Ruby Sapphire Map1"],
    ["MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2", "Cave Of Origin Unused Ruby Sapphire Map2"],
    ["MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3", "Cave Of Origin Unused Ruby Sapphire Map3"],
    ["MAP_GRASSY_SLAB", "Grassy Slab"],
    ["MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM", "Shoal Cave Low Tide Ice Room"],
    ["MAP_DEWFORD_TOWN", "Dewford Town"],
    ["MAP_PACIFIDLOG_TOWN", "Pacifidlog Town"],
    ["MAP_PETALBURG_CITY", "Petalburg City"],
    ["MAP_RUSTBORO_CITY", "Rustboro City"],
    ["MAP_SLATEPORT_CITY", "Slateport City"],
    ["MAP_SOOTOPOLIS_CITY", "Sootopolis City"],
    ["MAP_MOSSDEEP_CITY", "Mossdeep City"],
    ["MAP_EVER_GRANDE_CITY", "Ever Grande City"],
    ["MAP_SCORCHED_SLAB", "Scorched Slab"],
    ["MAP_SKY_PILLAR_1F", "Sky Pillar 1F"],
    ["MAP_SKY_PILLAR_2F", "Sky Pillar 2F"],
    ["MAP_SKY_PILLAR_3F", "Sky Pillar 3F"],
    ["MAP_SKY_PILLAR_4F", "Sky Pillar 4F"],
    ["MAP_SKY_PILLAR_5F", "Sky Pillar 5F"]
];

export default mapLocations;
